GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "order bread"
}

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "order chicken"
}

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "order guap"
}

###

DELETE http://localhost:3001/todo/delete/646ce76bc65da4a33a2b6f58

### 


PUT http://localhost:3001/todo/complete/646d326ccd3454d61658d219

